version: '3.4'

services:
  webapp:
    build: 
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_LANGSERVER_URL=http://localhost:5001
      - NEXT_PUBLIC_APISERVER_URL=https://2452-2600-1010-a020-4203-cddb-bd43-d44e-5b1a.ngrok-free.app/api
    depends_on:
      - api-gateway
    env_file: ./webapp/.env.docker
  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "/app"
    environment: 
      - GO111MODULE=on
      - PG_DBNAME=postgres
      - PG_USER=postgres
      - PG_HOST=db
      - PG_PASS=postgres
      - PG_PORT=5432
      - RUN_POSTGRES_MIGRATIONS=true
      - RUNNING_DEV_SERVER=true
      - HOST=api-gateway
      - PORT=8080
    entrypoint: "go run main.go"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api-gateway
      - db

volumes:
  db:
    driver: local