version: '3.4'

services:
  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "/app"
    environment: 
      - GO111MODULE=on
      - PG_DBNAME=postgres
      - PG_USER=postgres
      - PG_HOST=db
      - PG_PASS=postgres
      - PG_PORT=5432
      - RUN_POSTGRES_MIGRATIONS=true
      - RUNNING_DEV_SERVER=true
      - HOST=api-gateway
      - PORT=8080
    entrypoint: "go run main.go"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local